Repository FRC-1721/1721-RapidReact, pull requests merged in 2022-02, with the labels that each got.

#13 Refactor of tests
  .github/workflows/black-formatter.yml
  .github/workflows/build-workflow.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/publish-release.yml
  README.md
Labels: enhancement

#11 Fixes #8, Pigeon IMU
  rio/constants/robot_hardware.yaml
  rio/subsystems/drivetrain.py
Labels: enhancement

#14 Update for RTD
  README.md
  docs/conf.py
  docs/requirements.txt
Labels: documentation

#20 Add examples of programmer(s) to the docs
  docs/developing/developing.rst
  docs/developing/resources/AProgrammer.jpg
Labels: documentation

#17 Require python 3.10 when building for the rio
  rio/Pipfile
  rio/Pipfile.lock
Labels: bug

#18 Fixes rendering of swerve drive on dashboard
  dashboard/www/index.html
  rio/constants/robot_controls.yaml
Labels: bug

#12 Fixes #9, Bugfix/Swerve
  .gitignore
  README.md
  dashboard/Makefile
  rio/commands/nullauto.py
  rio/commands/test_button_action.py
  rio/constants/robot_controls.yaml
  rio/constants/robot_hardware.yaml
  rio/robot.py
  rio/robotcontainer.py
  rio/subsystems/drivetrain.py
Labels: bug

#31 Docs: Include NUC and RIO connectors in docs.
  docs/index.rst
  docs/wiring/resources/NUCWiring.png
  docs/wiring/resources/RIOWiring.png
  docs/wiring/wiring.rst
Labels: documentation

#30 Docs: Dev docs
  docs/developing/developing.rst
  docs/developing/resources/AProgrammer.jpg
  docs/developing/resources/AProgrammer.png
  docs/developing/resources/githubMerge.png
  docs/developing/resources/githubPullrequest.png
  docs/introduction/introduction.rst
  docs/introduction/resources/Robot.png
Labels: documentation

#45 Add reticle display to dashboard
  dashboard/src/index.js
  dashboard/www/resources/error.png
  dashboard/www/resources/no_signal.png
  dashboard/www/resources/swerveReticle.png
Labels: enhancement
