Repository FRC-1721/1721-RapidReact, pull requests merged in 2022-04, with the labels that each got.

#67 Fix for #7, track robot hash.
  dashboard/Pipfile
  rio/Pipfile.lock
  rio/robot.py
Labels: enhancement, pending test

#32 Climber: Feature/climber
  .gitignore
  rio/Pipfile
  rio/Pipfile.lock
  rio/commands/climb.py
  rio/constants/robot_hardware.yaml
  rio/robotcontainer.py
  rio/subsystems/climber.py
  rio/subsystems/drivetrain.py
Labels: new subsystem, pending test

#77 add movement to auto
  rio/autonomous/botchauto.py
  rio/autonomous/driveauto.py
  rio/autonomous/flywithwires.py
  rio/robotcontainer.py
Labels: pending test

#74 Hartford Event
  .gitignore
  dashboard/src/build_data-display.js
  dashboard/www/index.html
  rio/Pipfile.lock
  rio/autonomous/botchauto.py
  rio/autonomous/driveauto.py
  rio/autonomous/flywithwires.py
  rio/characterization/Yoke.json
  rio/commands/climb.py
  rio/commands/swing.py
  rio/constants/robot_controls.yaml
  rio/constants/robot_hardware.yaml
  rio/constants/robot_pid.yaml
  rio/robot.py
  rio/robotcontainer.py
  rio/subsystems/climber.py
  rio/subsystems/drivetrain.py
  rio/subsystems/yoke.py
Labels: event
